import { IInputSettings } from "../src/inputSettings";
import * as github from '@actions/github';
import { PullCheckRunner } from "../src/pullCheckRunner";

const mockGitHub = github.getOctokit("1234567890123456789012345678901234567890");

const settings = {
    localRepositoryOwner: "some-owner",
    localRepositoryName: "repo-name",
    claFilePath: "path/to/cla.json",
    branch: "master",
    octokitLocal: mockGitHub,
    workflowName: "WorkflowName"
} as IInputSettings;

const workflowRun = {
    "id": 154,
    "node_id": "MDExO4NDc3",
    "head_branch": "master",
    "head_sha": "d4ffbc49d428723242470c447d544918c4bd9f7e",
    "run_number": 21,
    "event": "issue_comment",
    "status": "completed",
    "conclusion": "success",
    "workflow_id": 1403,
    "url": "https://api.github.com/repos/owner/reponame/actions/runs/154864",
    "html_url": "https://github.com/owner/reponame/actions/runs/154864",
    "pull_requests": [],
    "created_at": "2020-06-04T22:45:26Z",
    "updated_at": "2020-06-04T22:45:42Z",
    "jobs_url": "https://api.github.com/repos/owner/reponame/actions/runs/154864/jobs",
    "logs_url": "https://api.github.com/repos/owner/reponame/actions/runs/154864/logs",
    "check_suite_url": "https://api.github.com/repos/owner/reponame/check-suites/757428205",
    "artifacts_url": "https://api.github.com/repos/owner/reponame/actions/runs/154864/artifacts",
    "cancel_url": "https://api.github.com/repos/owner/reponame/actions/runs/154864/cancel",
    "rerun_url": "https://api.github.com/repos/owner/reponame/actions/runs/154864/rerun",
    "workflow_url": "https://api.github.com/repos/owner/reponame/actions/workflows/1703",
    "head_commit": {
        "id": "d4ffbc49d428723242470c447d544918c4bd9f7e",
        "tree_id": "8dbce61624331ecb223a99245299c88f1267d19e",
        "message": "Merge pull request #4 from someuser/someuser-patch-3\n\nUpdate README.md",
        "timestamp": "2020-06-04T22:44:47Z",
        "author": {
            "name": "someuser",
            "email": "47404136+someuser@users.noreply.github.com"
        },
        "committer": {
            "name": "GitHub",
            "email": "noreply@github.com"
        }
    },
    "repository": {
        "id": 2682,
        "node_id": "MDEwOzU4ODI=",
        "name": "TestRepo",
        "full_name": "owner/reponame",
        "private": false,
        "owner": {
            "login": "someuser",
            "id": 4736,
            "node_id": "MDQ6MTM2",
            "avatar_url": "https://avatars2.githubusercontent.com/u/476?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/someuser",
            "html_url": "https://github.com/someuser",
            "followers_url": "https://api.github.com/users/someuser/followers",
            "following_url": "https://api.github.com/users/someuser/following{/other_user}",
            "gists_url": "https://api.github.com/users/someuser/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/someuser/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/someuser/subscriptions",
            "organizations_url": "https://api.github.com/users/someuser/orgs",
            "repos_url": "https://api.github.com/users/someuser/repos",
            "events_url": "https://api.github.com/users/someuser/events{/privacy}",
            "received_events_url": "https://api.github.com/users/someuser/received_events",
            "type": "User",
            "site_admin": false
        },
        "git_url": "",
        "ssh_url": "",
        "html_url": "https://github.com/owner/reponame",
        "description": "Test repo to check out CLA github action",
        "fork": false,
        "url": "https://api.github.com/repos/owner/reponame",
        "forks_url": "https://api.github.com/repos/owner/reponame/forks",
        "keys_url": "https://api.github.com/repos/owner/reponame/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/owner/reponame/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/owner/reponame/teams",
        "hooks_url": "https://api.github.com/repos/owner/reponame/hooks",
        "issue_events_url": "https://api.github.com/repos/owner/reponame/issues/events{/number}",
        "events_url": "https://api.github.com/repos/owner/reponame/events",
        "assignees_url": "https://api.github.com/repos/owner/reponame/assignees{/user}",
        "branches_url": "https://api.github.com/repos/owner/reponame/branches{/branch}",
        "tags_url": "https://api.github.com/repos/owner/reponame/tags",
        "blobs_url": "https://api.github.com/repos/owner/reponame/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/owner/reponame/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/owner/reponame/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/owner/reponame/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/owner/reponame/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/owner/reponame/languages",
        "stargazers_url": "https://api.github.com/repos/owner/reponame/stargazers",
        "contributors_url": "https://api.github.com/repos/owner/reponame/contributors",
        "subscribers_url": "https://api.github.com/repos/owner/reponame/subscribers",
        "subscription_url": "https://api.github.com/repos/owner/reponame/subscription",
        "commits_url": "https://api.github.com/repos/owner/reponame/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/owner/reponame/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/owner/reponame/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/owner/reponame/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/owner/reponame/contents/{+path}",
        "compare_url": "https://api.github.com/repos/owner/reponame/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/owner/reponame/merges",
        "archive_url": "https://api.github.com/repos/owner/reponame/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/owner/reponame/downloads",
        "issues_url": "https://api.github.com/repos/owner/reponame/issues{/number}",
        "pulls_url": "https://api.github.com/repos/owner/reponame/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/owner/reponame/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/owner/reponame/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/owner/reponame/labels{/name}",
        "releases_url": "https://api.github.com/repos/owner/reponame/releases{/id}",
        "deployments_url": "https://api.github.com/repos/owner/reponame/deployments"
    },
    "head_repository": {
        "id": 26882,
        "node_id": "MDEwOlJlcG9kyMzU4ODI=",
        "name": "TestRepo",
        "full_name": "owner/reponame",
        "private": false,
        "owner": {
            "login": "someuser",
            "id": 47136,
            "node_id": "MDQ6VXA0MTM2",
            "avatar_url": "https://avatars2.githubusercontent.com/u/47404136?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/someuser",
            "html_url": "https://github.com/someuser",
            "followers_url": "https://api.github.com/users/someuser/followers",
            "following_url": "https://api.github.com/users/someuser/following{/other_user}",
            "gists_url": "https://api.github.com/users/someuser/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/someuser/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/someuser/subscriptions",
            "organizations_url": "https://api.github.com/users/someuser/orgs",
            "repos_url": "https://api.github.com/users/someuser/repos",
            "events_url": "https://api.github.com/users/someuser/events{/privacy}",
            "received_events_url": "https://api.github.com/users/someuser/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/owner/reponame",
        "description": "Test repo to check out CLA github action",
        "fork": false,
        "url": "https://api.github.com/repos/owner/reponame",
        "forks_url": "https://api.github.com/repos/owner/reponame/forks",
        "keys_url": "https://api.github.com/repos/owner/reponame/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/owner/reponame/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/owner/reponame/teams",
        "hooks_url": "https://api.github.com/repos/owner/reponame/hooks",
        "issue_events_url": "https://api.github.com/repos/owner/reponame/issues/events{/number}",
        "events_url": "https://api.github.com/repos/owner/reponame/events",
        "assignees_url": "https://api.github.com/repos/owner/reponame/assignees{/user}",
        "branches_url": "https://api.github.com/repos/owner/reponame/branches{/branch}",
        "tags_url": "https://api.github.com/repos/owner/reponame/tags",
        "blobs_url": "https://api.github.com/repos/owner/reponame/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/owner/reponame/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/owner/reponame/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/owner/reponame/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/owner/reponame/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/owner/reponame/languages",
        "stargazers_url": "https://api.github.com/repos/owner/reponame/stargazers",
        "contributors_url": "https://api.github.com/repos/owner/reponame/contributors",
        "subscribers_url": "https://api.github.com/repos/owner/reponame/subscribers",
        "subscription_url": "https://api.github.com/repos/owner/reponame/subscription",
        "commits_url": "https://api.github.com/repos/owner/reponame/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/owner/reponame/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/owner/reponame/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/owner/reponame/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/owner/reponame/contents/{+path}",
        "compare_url": "https://api.github.com/repos/owner/reponame/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/owner/reponame/merges",
        "archive_url": "https://api.github.com/repos/owner/reponame/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/owner/reponame/downloads",
        "issues_url": "https://api.github.com/repos/owner/reponame/issues{/number}",
        "pulls_url": "https://api.github.com/repos/owner/reponame/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/owner/reponame/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/owner/reponame/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/owner/reponame/labels{/name}",
        "releases_url": "https://api.github.com/repos/owner/reponame/releases{/id}",
        "deployments_url": "https://api.github.com/repos/owner/reponame/deployments"
    }
}

const pullRequest = {
    "url": "https://api.github.com/repos/octocat/Hello-World/pulls/1347",
    "id": 1,
    "node_id": "MDExOlB1bGxSZXF1ZXN0MQ==",
    "html_url": "https://github.com/octocat/Hello-World/pull/1347",
    "diff_url": "https://github.com/octocat/Hello-World/pull/1347.diff",
    "patch_url": "https://github.com/octocat/Hello-World/pull/1347.patch",
    "issue_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347",
    "commits_url": "https://api.github.com/repos/octocat/Hello-World/pulls/1347/commits",
    "review_comments_url": "https://api.github.com/repos/octocat/Hello-World/pulls/1347/comments",
    "review_comment_url": "https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/comments",
    "statuses_url": "https://api.github.com/repos/octocat/Hello-World/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e",
    "number": 1347,
    "state": "open",
    "locked": true,
    "title": "Amazing new feature",
    "user": {
        "login": "octocat",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://github.com/images/error/octocat_happy.gif",
        "gravatar_id": "",
        "url": "https://api.github.com/users/octocat",
        "html_url": "https://github.com/octocat",
        "followers_url": "https://api.github.com/users/octocat/followers",
        "following_url": "https://api.github.com/users/octocat/following{/other_user}",
        "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
        "organizations_url": "https://api.github.com/users/octocat/orgs",
        "repos_url": "https://api.github.com/users/octocat/repos",
        "events_url": "https://api.github.com/users/octocat/events{/privacy}",
        "received_events_url": "https://api.github.com/users/octocat/received_events",
        "type": "User",
        "site_admin": false
    },
    "body": "Please pull these awesome changes in!",
    "labels": [
        {
            "id": 208045946,
            "node_id": "MDU6TGFiZWwyMDgwNDU5NDY=",
            "url": "https://api.github.com/repos/octocat/Hello-World/labels/bug",
            "name": "bug",
            "description": "Something isn't working",
            "color": "f29513",
            "default": true
        }
    ],
    "milestone": {
        "url": "https://api.github.com/repos/octocat/Hello-World/milestones/1",
        "html_url": "https://github.com/octocat/Hello-World/milestones/v1.0",
        "labels_url": "https://api.github.com/repos/octocat/Hello-World/milestones/1/labels",
        "id": 1002604,
        "node_id": "MDk6TWlsZXN0b25lMTAwMjYwNA==",
        "number": 1,
        "state": "open",
        "title": "v1.0",
        "description": "Tracking milestone for version 1.0",
        "creator": {
            "login": "octocat",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://github.com/images/error/octocat_happy.gif",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "open_issues": 4,
        "closed_issues": 8,
        "created_at": "2011-04-10T20:09:31Z",
        "updated_at": "2014-03-03T18:58:10Z",
        "closed_at": "2013-02-12T13:22:01Z",
        "due_on": "2012-10-09T23:39:01Z"
    },
    "active_lock_reason": "too heated",
    "created_at": "2011-01-26T19:01:12Z",
    "updated_at": "2011-01-26T19:01:12Z",
    "closed_at": "2011-01-26T19:01:12Z",
    "merged_at": "2011-01-26T19:01:12Z",
    "merge_commit_sha": "e5bd3914e2e596debea16f433f57875b5b90bcd6",
    "assignee": {
        "login": "octocat",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://github.com/images/error/octocat_happy.gif",
        "gravatar_id": "",
        "url": "https://api.github.com/users/octocat",
        "html_url": "https://github.com/octocat",
        "followers_url": "https://api.github.com/users/octocat/followers",
        "following_url": "https://api.github.com/users/octocat/following{/other_user}",
        "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
        "organizations_url": "https://api.github.com/users/octocat/orgs",
        "repos_url": "https://api.github.com/users/octocat/repos",
        "events_url": "https://api.github.com/users/octocat/events{/privacy}",
        "received_events_url": "https://api.github.com/users/octocat/received_events",
        "type": "User",
        "site_admin": false
    },
    "assignees": [
        {
            "login": "octocat",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://github.com/images/error/octocat_happy.gif",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        {
            "login": "hubot",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://github.com/images/error/hubot_happy.gif",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hubot",
            "html_url": "https://github.com/hubot",
            "followers_url": "https://api.github.com/users/hubot/followers",
            "following_url": "https://api.github.com/users/hubot/following{/other_user}",
            "gists_url": "https://api.github.com/users/hubot/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/hubot/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/hubot/subscriptions",
            "organizations_url": "https://api.github.com/users/hubot/orgs",
            "repos_url": "https://api.github.com/users/hubot/repos",
            "events_url": "https://api.github.com/users/hubot/events{/privacy}",
            "received_events_url": "https://api.github.com/users/hubot/received_events",
            "type": "User",
            "site_admin": true
        }
    ],
    "requested_reviewers": [
        {
            "login": "other_user",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://github.com/images/error/other_user_happy.gif",
            "gravatar_id": "",
            "url": "https://api.github.com/users/other_user",
            "html_url": "https://github.com/other_user",
            "followers_url": "https://api.github.com/users/other_user/followers",
            "following_url": "https://api.github.com/users/other_user/following{/other_user}",
            "gists_url": "https://api.github.com/users/other_user/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/other_user/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/other_user/subscriptions",
            "organizations_url": "https://api.github.com/users/other_user/orgs",
            "repos_url": "https://api.github.com/users/other_user/repos",
            "events_url": "https://api.github.com/users/other_user/events{/privacy}",
            "received_events_url": "https://api.github.com/users/other_user/received_events",
            "type": "User",
            "site_admin": false
        }
    ],
    "requested_teams": [
        {
            "id": 1,
            "node_id": "MDQ6VGVhbTE=",
            "url": "https://api.github.com/teams/1",
            "html_url": "https://api.github.com/teams/justice-league",
            "name": "Justice League",
            "slug": "justice-league",
            "description": "A great team.",
            "privacy": "closed",
            "permission": "admin",
            "members_url": "https://api.github.com/teams/1/members{/member}",
            "repositories_url": "https://api.github.com/teams/1/repos",
            "parent": "null"
        }
    ],
    "head": {
        "label": "octocat:new-topic",
        "ref": "new-topic",
        "sha": "6dcb09b5b57875f334f61aebed695e2e4193db5e",
        "user": {
            "login": "octocat",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://github.com/images/error/octocat_happy.gif",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "repo": {
            "id": 1296269,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
            "name": "Hello-World",
            "full_name": "octocat/Hello-World",
            "owner": {
                "login": "octocat",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "avatar_url": "https://github.com/images/error/octocat_happy.gif",
                "gravatar_id": "",
                "url": "https://api.github.com/users/octocat",
                "html_url": "https://github.com/octocat",
                "followers_url": "https://api.github.com/users/octocat/followers",
                "following_url": "https://api.github.com/users/octocat/following{/other_user}",
                "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
                "organizations_url": "https://api.github.com/users/octocat/orgs",
                "repos_url": "https://api.github.com/users/octocat/repos",
                "events_url": "https://api.github.com/users/octocat/events{/privacy}",
                "received_events_url": "https://api.github.com/users/octocat/received_events",
                "type": "User",
                "site_admin": false
            },
            "private": false,
            "html_url": "https://github.com/octocat/Hello-World",
            "description": "This your first repo!",
            "fork": false,
            "url": "https://api.github.com/repos/octocat/Hello-World",
            "archive_url": "http://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}",
            "assignees_url": "http://api.github.com/repos/octocat/Hello-World/assignees{/user}",
            "blobs_url": "http://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}",
            "branches_url": "http://api.github.com/repos/octocat/Hello-World/branches{/branch}",
            "collaborators_url": "http://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}",
            "comments_url": "http://api.github.com/repos/octocat/Hello-World/comments{/number}",
            "commits_url": "http://api.github.com/repos/octocat/Hello-World/commits{/sha}",
            "compare_url": "http://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}",
            "contents_url": "http://api.github.com/repos/octocat/Hello-World/contents/{+path}",
            "contributors_url": "http://api.github.com/repos/octocat/Hello-World/contributors",
            "deployments_url": "http://api.github.com/repos/octocat/Hello-World/deployments",
            "downloads_url": "http://api.github.com/repos/octocat/Hello-World/downloads",
            "events_url": "http://api.github.com/repos/octocat/Hello-World/events",
            "forks_url": "http://api.github.com/repos/octocat/Hello-World/forks",
            "git_commits_url": "http://api.github.com/repos/octocat/Hello-World/git/commits{/sha}",
            "git_refs_url": "http://api.github.com/repos/octocat/Hello-World/git/refs{/sha}",
            "git_tags_url": "http://api.github.com/repos/octocat/Hello-World/git/tags{/sha}",
            "git_url": "git:github.com/octocat/Hello-World.git",
            "issue_comment_url": "http://api.github.com/repos/octocat/Hello-World/issues/comments{/number}",
            "issue_events_url": "http://api.github.com/repos/octocat/Hello-World/issues/events{/number}",
            "issues_url": "http://api.github.com/repos/octocat/Hello-World/issues{/number}",
            "keys_url": "http://api.github.com/repos/octocat/Hello-World/keys{/key_id}",
            "labels_url": "http://api.github.com/repos/octocat/Hello-World/labels{/name}",
            "languages_url": "http://api.github.com/repos/octocat/Hello-World/languages",
            "merges_url": "http://api.github.com/repos/octocat/Hello-World/merges",
            "milestones_url": "http://api.github.com/repos/octocat/Hello-World/milestones{/number}",
            "notifications_url": "http://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}",
            "pulls_url": "http://api.github.com/repos/octocat/Hello-World/pulls{/number}",
            "releases_url": "http://api.github.com/repos/octocat/Hello-World/releases{/id}",
            "ssh_url": "git@github.com:octocat/Hello-World.git",
            "stargazers_url": "http://api.github.com/repos/octocat/Hello-World/stargazers",
            "statuses_url": "http://api.github.com/repos/octocat/Hello-World/statuses/{sha}",
            "subscribers_url": "http://api.github.com/repos/octocat/Hello-World/subscribers",
            "subscription_url": "http://api.github.com/repos/octocat/Hello-World/subscription",
            "tags_url": "http://api.github.com/repos/octocat/Hello-World/tags",
            "teams_url": "http://api.github.com/repos/octocat/Hello-World/teams",
            "trees_url": "http://api.github.com/repos/octocat/Hello-World/git/trees{/sha}",
            "clone_url": "https://github.com/octocat/Hello-World.git",
            "mirror_url": "git:git.example.com/octocat/Hello-World",
            "hooks_url": "http://api.github.com/repos/octocat/Hello-World/hooks",
            "svn_url": "https://svn.github.com/octocat/Hello-World",
            "homepage": "https://github.com",
            "language": "null",
            "forks_count": 9,
            "stargazers_count": 80,
            "watchers_count": 80,
            "size": 108,
            "default_branch": "master",
            "open_issues_count": 0,
            "is_template": true,
            "topics": [
                "octocat",
                "atom",
                "electron",
                "api"
            ],
            "has_issues": true,
            "has_projects": true,
            "has_wiki": true,
            "has_pages": false,
            "has_downloads": true,
            "archived": false,
            "disabled": false,
            "visibility": "public",
            "pushed_at": "2011-01-26T19:06:43Z",
            "created_at": "2011-01-26T19:01:12Z",
            "updated_at": "2011-01-26T19:14:43Z",
            "permissions": {
                "admin": false,
                "push": false,
                "pull": true
            },
            "allow_rebase_merge": true,
            "template_repository": "null",
            "temp_clone_token": "ABTLWHOULUVAXGTRYU7OC2876QJ2O",
            "allow_squash_merge": true,
            "allow_merge_commit": true,
            "subscribers_count": 42,
            "network_count": 0
        }
    },
    "base": {
        "label": "octocat:master",
        "ref": "master",
        "sha": "6dcb09b5b57875f334f61aebed695e2e4193db5e",
        "user": {
            "login": "octocat",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://github.com/images/error/octocat_happy.gif",
            "gravatar_id": "",
            "url": "https://api.github.com/users/octocat",
            "html_url": "https://github.com/octocat",
            "followers_url": "https://api.github.com/users/octocat/followers",
            "following_url": "https://api.github.com/users/octocat/following{/other_user}",
            "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
            "organizations_url": "https://api.github.com/users/octocat/orgs",
            "repos_url": "https://api.github.com/users/octocat/repos",
            "events_url": "https://api.github.com/users/octocat/events{/privacy}",
            "received_events_url": "https://api.github.com/users/octocat/received_events",
            "type": "User",
            "site_admin": false
        },
        "repo": {
            "id": 1296269,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
            "name": "Hello-World",
            "full_name": "octocat/Hello-World",
            "owner": {
                "login": "octocat",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "avatar_url": "https://github.com/images/error/octocat_happy.gif",
                "gravatar_id": "",
                "url": "https://api.github.com/users/octocat",
                "html_url": "https://github.com/octocat",
                "followers_url": "https://api.github.com/users/octocat/followers",
                "following_url": "https://api.github.com/users/octocat/following{/other_user}",
                "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
                "organizations_url": "https://api.github.com/users/octocat/orgs",
                "repos_url": "https://api.github.com/users/octocat/repos",
                "events_url": "https://api.github.com/users/octocat/events{/privacy}",
                "received_events_url": "https://api.github.com/users/octocat/received_events",
                "type": "User",
                "site_admin": false
            },
            "private": false,
            "html_url": "https://github.com/octocat/Hello-World",
            "description": "This your first repo!",
            "fork": false,
            "url": "https://api.github.com/repos/octocat/Hello-World",
            "archive_url": "http://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}",
            "assignees_url": "http://api.github.com/repos/octocat/Hello-World/assignees{/user}",
            "blobs_url": "http://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}",
            "branches_url": "http://api.github.com/repos/octocat/Hello-World/branches{/branch}",
            "collaborators_url": "http://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}",
            "comments_url": "http://api.github.com/repos/octocat/Hello-World/comments{/number}",
            "commits_url": "http://api.github.com/repos/octocat/Hello-World/commits{/sha}",
            "compare_url": "http://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}",
            "contents_url": "http://api.github.com/repos/octocat/Hello-World/contents/{+path}",
            "contributors_url": "http://api.github.com/repos/octocat/Hello-World/contributors",
            "deployments_url": "http://api.github.com/repos/octocat/Hello-World/deployments",
            "downloads_url": "http://api.github.com/repos/octocat/Hello-World/downloads",
            "events_url": "http://api.github.com/repos/octocat/Hello-World/events",
            "forks_url": "http://api.github.com/repos/octocat/Hello-World/forks",
            "git_commits_url": "http://api.github.com/repos/octocat/Hello-World/git/commits{/sha}",
            "git_refs_url": "http://api.github.com/repos/octocat/Hello-World/git/refs{/sha}",
            "git_tags_url": "http://api.github.com/repos/octocat/Hello-World/git/tags{/sha}",
            "git_url": "git:github.com/octocat/Hello-World.git",
            "issue_comment_url": "http://api.github.com/repos/octocat/Hello-World/issues/comments{/number}",
            "issue_events_url": "http://api.github.com/repos/octocat/Hello-World/issues/events{/number}",
            "issues_url": "http://api.github.com/repos/octocat/Hello-World/issues{/number}",
            "keys_url": "http://api.github.com/repos/octocat/Hello-World/keys{/key_id}",
            "labels_url": "http://api.github.com/repos/octocat/Hello-World/labels{/name}",
            "languages_url": "http://api.github.com/repos/octocat/Hello-World/languages",
            "merges_url": "http://api.github.com/repos/octocat/Hello-World/merges",
            "milestones_url": "http://api.github.com/repos/octocat/Hello-World/milestones{/number}",
            "notifications_url": "http://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}",
            "pulls_url": "http://api.github.com/repos/octocat/Hello-World/pulls{/number}",
            "releases_url": "http://api.github.com/repos/octocat/Hello-World/releases{/id}",
            "ssh_url": "git@github.com:octocat/Hello-World.git",
            "stargazers_url": "http://api.github.com/repos/octocat/Hello-World/stargazers",
            "statuses_url": "http://api.github.com/repos/octocat/Hello-World/statuses/{sha}",
            "subscribers_url": "http://api.github.com/repos/octocat/Hello-World/subscribers",
            "subscription_url": "http://api.github.com/repos/octocat/Hello-World/subscription",
            "tags_url": "http://api.github.com/repos/octocat/Hello-World/tags",
            "teams_url": "http://api.github.com/repos/octocat/Hello-World/teams",
            "trees_url": "http://api.github.com/repos/octocat/Hello-World/git/trees{/sha}",
            "clone_url": "https://github.com/octocat/Hello-World.git",
            "mirror_url": "git:git.example.com/octocat/Hello-World",
            "hooks_url": "http://api.github.com/repos/octocat/Hello-World/hooks",
            "svn_url": "https://svn.github.com/octocat/Hello-World",
            "homepage": "https://github.com",
            "language": "null",
            "forks_count": 9,
            "stargazers_count": 80,
            "watchers_count": 80,
            "size": 108,
            "default_branch": "master",
            "open_issues_count": 0,
            "is_template": true,
            "topics": [
                "octocat",
                "atom",
                "electron",
                "api"
            ],
            "has_issues": true,
            "has_projects": true,
            "has_wiki": true,
            "has_pages": false,
            "has_downloads": true,
            "archived": false,
            "disabled": false,
            "visibility": "public",
            "pushed_at": "2011-01-26T19:06:43Z",
            "created_at": "2011-01-26T19:01:12Z",
            "updated_at": "2011-01-26T19:14:43Z",
            "permissions": {
                "admin": false,
                "push": false,
                "pull": true
            },
            "allow_rebase_merge": true,
            "template_repository": "null",
            "temp_clone_token": "ABTLWHOULUVAXGTRYU7OC2876QJ2O",
            "allow_squash_merge": true,
            "allow_merge_commit": true,
            "subscribers_count": 42,
            "network_count": 0
        }
    },
    "_links": {
        "self": {
            "href": "https://api.github.com/repos/octocat/Hello-World/pulls/1347"
        },
        "html": {
            "href": "https://github.com/octocat/Hello-World/pull/1347"
        },
        "issue": {
            "href": "https://api.github.com/repos/octocat/Hello-World/issues/1347"
        },
        "comments": {
            "href": "https://api.github.com/repos/octocat/Hello-World/issues/1347/comments"
        },
        "review_comments": {
            "href": "https://api.github.com/repos/octocat/Hello-World/pulls/1347/comments"
        },
        "review_comment": {
            "href": "https://api.github.com/repos/octocat/Hello-World/pulls/comments{/number}"
        },
        "commits": {
            "href": "https://api.github.com/repos/octocat/Hello-World/pulls/1347/commits"
        },
        "statuses": {
            "href": "https://api.github.com/repos/octocat/Hello-World/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e"
        }
    },
    "author_association": "OWNER",
    "draft": false,
    "merged": false,
    "mergeable": true,
    "rebaseable": true,
    "mergeable_state": "clean",
    "merged_by": {
        "login": "octocat",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://github.com/images/error/octocat_happy.gif",
        "gravatar_id": "",
        "url": "https://api.github.com/users/octocat",
        "html_url": "https://github.com/octocat",
        "followers_url": "https://api.github.com/users/octocat/followers",
        "following_url": "https://api.github.com/users/octocat/following{/other_user}",
        "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
        "organizations_url": "https://api.github.com/users/octocat/orgs",
        "repos_url": "https://api.github.com/users/octocat/repos",
        "events_url": "https://api.github.com/users/octocat/events{/privacy}",
        "received_events_url": "https://api.github.com/users/octocat/received_events",
        "type": "User",
        "site_admin": false
    },
    "comments": 10,
    "review_comments": 0,
    "maintainer_can_modify": true,
    "commits": 3,
    "additions": 100,
    "deletions": 3,
    "changed_files": 5
};

function mockWith(hasRuns = false): [PullCheckRunner, any, any, any, any] {
    const pullCheckRunner = new PullCheckRunner(settings);

    const listWorkflowRunsSpy = jest.spyOn(mockGitHub.actions, 'listWorkflowRuns')
        .mockImplementation(async (params) => ({
            headers: {
                date: "",
                "x-Octokit-media-type": "",
                "x-Octokit-request-id": "",
                "x-ratelimit-limit": "",
                "x-ratelimit-remaining": "",
                "x-ratelimit-reset": "",
                link: "",
                "last-modified": "",
                etag: "",
                status: "200",
            },
            status: 200,
            url: "",
            data: {
                total_count: hasRuns ? 1 : 0,
                workflow_runs: hasRuns ? [workflowRun] : []
            },
        }));

    const listRepoWorkflowsSpy = jest.spyOn(mockGitHub.actions, 'listRepoWorkflows')
        .mockImplementation(async (params) => ({
            headers: {
                date: "",
                "x-Octokit-media-type": "",
                "x-Octokit-request-id": "",
                "x-ratelimit-limit": "",
                "x-ratelimit-remaining": "",
                "x-ratelimit-reset": "",
                link: "",
                "last-modified": "",
                etag: "",
                status: "200",
            },
            status: 200,
            url: "",
            data: {
                total_count: 1,
                workflows: [{
                    badge_url: "",
                    created_at: "",
                    html_url: "",
                    id: 12345,
                    name: settings.workflowName,
                    node_id: "lakrjg",
                    path: ".github/workflows/clabot.yml",
                    state: "active",
                    updated_at: "",
                    url: "",
                }]
            },
        }));

    const requestSpy = jest.spyOn(mockGitHub.actions, 'reRunWorkflow')
        .mockImplementation(async (params) => ({
            headers: {
                date: "",
                "x-Octokit-media-type": "",
                "x-Octokit-request-id": "",
                "x-ratelimit-limit": "",
                "x-ratelimit-remaining": "",
                "x-ratelimit-reset": "",
                link: "",
                "last-modified": "",
                etag: "",
                status: "200",
            },
            status: 200,
            url: "",
            data: {}
        }));

    const pullGetSpy = jest.spyOn(mockGitHub.pulls, 'get')
        .mockImplementation(async () => ({
            headers: {
                date: "",
                "x-Octokit-media-type": "",
                "x-Octokit-request-id": "",
                "x-ratelimit-limit": "",
                "x-ratelimit-remaining": "",
                "x-ratelimit-reset": "",
                link: "",
                "last-modified": "",
                etag: "",
                status: "200",
            },
            status: 200,
            url: "",
            data: pullRequest
        }));

    return [pullCheckRunner, listWorkflowRunsSpy, listRepoWorkflowsSpy, requestSpy, pullGetSpy];
}

it("Doesn't fail if it can't find an old run", async () => {
    const [pullCheckRunner, listWorkflowRunsSpy, listRepoWorkflowsSpy, requestSpy, pullGetSpy] = mockWith(false);

    await pullCheckRunner.rerunLastCheck();

    expect(listRepoWorkflowsSpy).toHaveBeenCalledTimes(1);
    expect(listWorkflowRunsSpy).toHaveBeenCalledTimes(1);
    expect(pullGetSpy).toHaveBeenCalledTimes(1);
    expect(requestSpy).toHaveBeenCalledTimes(0);
});

it("Works if it does find an old run", async () => {
    const [pullCheckRunner, listWorkflowRunsSpy, listRepoWorkflowsSpy, requestSpy, pullGetSpy] = mockWith(true);

    await pullCheckRunner.rerunLastCheck();

    expect(listRepoWorkflowsSpy).toHaveBeenCalledTimes(1);
    expect(listWorkflowRunsSpy).toHaveBeenCalledTimes(1);
    expect(pullGetSpy).toHaveBeenCalledTimes(1);
    expect(requestSpy).toHaveBeenCalledTimes(1);
});
