name: Build and Test

on:
  push:
   branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm install
        run: npm ci

      - name: Npm build
        run: npm run build

      - name: Npm test
        run: npm run test
      
      - name: Generate dist
        run: npm run dist
      
      - name: Update dist
        uses: Roblox-ActionsCache/EndBug-add-and-commit@v7
        with:
          author_name: GitHub Actions Bot
          message: Updates the dist
          add: dist
  
  test:
    runs-on: ubuntu-latest
    needs: build
    # CLA bot comments on pull requests and infers PR number from context.
    # Running on the default branch causes the actiont to fail since it's not running in a PR.
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
    steps:
      - uses: actions/checkout@v3

      - name: Test CLA Bot Action
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          branch: master
          path-to-signatures: "signatures/cla.json"
          whitelist: "cliffchapmanrbx"
          use-remote-repo: true
          remote-repo-name: "roblox/cla-bot-store"
          remote-repo-pat: ${{ secrets.CLA_REMOTE_REPO_PAT }}
          url-to-cladocument: "https://roblox.github.io/cla-bot-store/"
