name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  call-clabot-workflow:
    uses: Roblox/cla-signature-bot/.github/workflows/clabot-workflow.yml@73db6348cf54e038417c862fdb59cac90faea414
    with:
      use-remote-repo: true
      whitelist: "cliffchapmanrbx"
      remote-repo-name: "roblox/cla-bot-store"
    secrets: inherit
