name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  call-clabot-workflow:
    uses: Roblox/cla-signature-bot/.github/workflows/clabot-workflow.yml@b6dc9b397764e7fce315c1c8e93ccf7a2e8cfa6a
    with:
      whitelist: "cliffchapmanrbx"
    secrets: inherit
