name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  clabot:
    uses: Roblox/cla-signature-bot/.github/workflows/clabot-workflow.yml@580f57d62cd843708e8ad0d2b351de4a61d5070c
    with:
      whitelist: "cliffchapmanrbx"
      use-remote-repo: true
      remote-repo-name: "roblox/cla-bot-store"
    secrets: inherit
