name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  call-clabot-workflow:
    uses: Roblox/cla-signature-bot/.github/workflows/clabot-workflow.yml@1909bf69b91d1f7529e0d5f7d1390ab6576fc1be
    with:
      whitelist: "cliffchapmanrbx"
      use-remote-repo: true
      remote-repo-name: "roblox/cla-bot-store"
    secrets: inherit
