name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: "Run CLA Bot"
        uses: roblox/cla-signature-bot@c74f44b6bcdb5077e5f092744b74669b457b2492
        env: 
          GITHUB_TOKEN: ${{ github.token }}
        with:
          branch: master
          path-to-signatures: "signatures/cla.json"
          whitelist: "cliffchapmanrbx"
          use-remote-repo: true
          remote-repo-name: "roblox/cla-bot-store"
          remote-repo-pat: ${{ secrets.CLA_REMOTE_REPO_PAT }}
          url-to-cladocument: "https://roblox.github.io/cla-bot-store/"

  call-clabot-workflow:
    uses: Roblox/cla-signature-bot/.github/workflows/clabot-workflow.yml@c74f44b6bcdb5077e5f092744b74669b457b2492
    with:
      whitelist: "cliffchapmanrbx"
      use-remote-repo: true
      remote-repo-name: "roblox/cla-bot-store"
    secrets: inherit
