name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  call-clabot-workflow:
    uses: Roblox/cla-signature-bot/.github/workflows/clabot-workflow.yml@53ba9d29ad8c876bf37e101583b7c495ee3f2d8a
    with:
      whitelist: "cliffchapmanrbx"
      use-remote-repo: true
      remote-repo-name: "roblox/cla-bot-store"
    secrets: inherit
